baseURL: http://nguyenvukhang.github.io
languageCode: en-us
title: distillery
publishDir: docs
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: distillery
    description: "khang's blog"
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
    label:
        text: "distillery"
        # icon: /resources/icons/compass.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: distillery
        subtitle: >
            Welcome to my blog. \

            **distillery** is a space where I curate my life experiences and compile them into an archive of useful knowledge.


        imageUrl: "/icons/compass.png"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            Welcome to my blog.

            - **distillery** is a space where I curate my life experiences and compile them into an archive of useful knowledge.

    socialIcons:
      # - name: twitter
      #   url: "https://twitter.com/"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/7943235/nguyễn-vũ-khang"
        - name: github
          url: "https://github.com/NguyenVuKhang"
      # - name: discord
      #   url: "https://discordapp.com/users/khang#0805"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: example
          name: example.org
          url: https://www.google.com
          weight: 30
